### PR TITLE
Support subdirectory deployment and fix API path handling

### LINKED ISSUE #301: 请问能否支持子目录部署？
请问项目能支持子目录部署吗？我将项目部署成 https://example.com/nextaidrawio ，页面无法正常显示...

### PR DESCRIPTION
**Pull request by Biki-dev**
## Summary
This PR adds support for deploying the app under a subdirectory by introducing the `NEXT_PUBLIC_BASE_PATH` configuration and updating client-side asset and API requests to respect the base path.

## Changes
- Added `basePath` to `next.config.ts` (reads `NEXT_PUBLIC_BASE_PATH`)
- New utility `lib/base-path.ts` with `getApiEndpoint()` and `getAssetUrl()`
- Updated client-side API calls to use `getApiEndpoint()`
- Updated static asset usage to use `getAssetUrl()`

resolves #301

### CODE REVIEW

**Comment by DayuanJiang** [comment]
Hey, noticed #313 is working on the same feature. Would you two like to collaborate? @Biki-dev's utility approach + @zhangxin-github's about page coverage could make a more complete solution.

File: lib/base-path.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ * This is used for subdirectory deployment support
+ *
+ * Example: If deployed at https://example.com/nextaidrawio, this returns "/nextaidrawio"
+ * For root deployment, this returns ""
+ *
+ * Set NEXT_PUBLIC_BASE_PATH environment variable to your subdirectory path (e.g., /nextaidrawio)
+ */
+export function getBasePath(): string {
+    // Only available on client side
+    if (typeof window === "undefined") {
```
Comment (DayuanJiang) [inline lib/base-path.ts]: Why is this check needed?

File: app/manifest.ts [hunk 2]
```diff
@@ -1,27 +1,28 @@
...
+        short_name: "AIDraw.io",
+        description:
+            "Create AWS architecture diagrams, flowcharts, and technical diagrams using AI. Free online tool integrating draw.io with AI assistance for professional diagram creation.",
+        start_url: process.env.NEXT_PUBLIC_BASE_PATH || "/",
+        display: "standalone",
+        background_color: "#f9fafb",
+        theme_color: "#171d26",
+        icons: [
+            {
+                src: "/favicon-192x192.png",
```
Comment (DayuanJiang) [inline app/manifest.ts]: The icon path alse need be updated with the `basePath`

**Comment by Biki-dev** [comment]
> Hey, noticed #313 is working on the same feature. Would you two like to collaborate? @Biki-dev's utility approach + @zhangxin-github's about page coverage could make a more complete solution.

@DayuanJiang sure

File: lib/base-path.ts (hunk 1 above)
Comment (Biki-dev) [reply lib/base-path.ts]: Because window does not exist on the server, the check typeof window === "undefined" is there to prevent errors during SSR.If you want the function to function the same on both the server and the client, it can be remove also. The environment variable is available during build/SSR time.

File: app/manifest.ts [hunk 3]
```diff
@@ -6,19 +6,19 @@ export default function manifest(): MetadataRoute.Manifest {
         short_name: "AIDraw.io",
         description:
             "Create AWS architecture diagrams, flowcharts, and technical diagrams using AI. Free online tool integrating draw.io with AI assistance for professional diagram creation.",
-        start_url: "/",
+        start_url: process.env.NEXT_PUBLIC_BASE_PATH || "/",
         display: "standalone",
```
Comment (DayuanJiang) [inline app/manifest.ts:10]: I realized that it is better to use `getAssetUrl("/favicon-192x192.png")` since `process.env.NEXT_PUBLIC_BASE_PATH` can be undefine.

Also for line 15

**Comment by DayuanJiang** [comment]
Thanks for the fix. Merged.
