### PR TITLE
Show success toast after saving diagram

### LINKED ISSUE #479: No success feedback after tapping Save button - Add confirmation toast/message
**Description**  
After tapping the "Save" button, the save functionality executes successfully, but there is no visual confirmation or popup message shown to the user. This leaves users uncertain whether the action completed, potentially leading to repeated taps or confusion.

**Steps to Reproduce**  
1. Navigate to the save-enabled screen.  
2. Make any changes.  
3. Tap the "Save" button.  
4. Observe no popup, toast, or message appears post-save.

**Expected Behavior**  
A subtle success indicator should appear immediately after the save completes, such as a green toast notification saying "Saved successfully!" positioned in the bottom-right corner of the screen. This should auto-dismiss after 2-3 seconds.

**Actual Behavior**  
Save works (no errors), but no feedback is provided. The UI simply remains unchanged, and the button doesn't indicate completion .

**Suggestion**  
Implement a non-intrusive green toast notification (e.g., using a library like react-hot-toast or native UI components) that slides in from the bottom-right with the text "Saved!" and a checkmark icon. Keep it brief and dismissible to avoid disrupting the user flow.

Image

### PR DESCRIPTION
**Pull request by RohitChavan16**
Fixes #479 

### What this PR does

This PR adds a non-intrusive success toast notification after a diagram is saved.

Currently, the save operation completes successfully but provides no visual feedback,
which can leave users unsure whether the action finished. This change shows a brief
success toast once the save/export completes, improving clarity without disrupting
the user workflow.

### Details
- Displays a green success toast after a successful save
- Toast appears in the bottom-right corner
- Auto-dismisses after ~2.5 seconds
- Triggered only after the download/export is initiated

### Why this change
Providing immediate visual confirmation improves UX and prevents repeated save
attempts caused by uncertainty.

### Testing
- Verified the save flow via code path inspection
- Toast is triggered only after a successful save/export

### CODE REVIEW

**Comment by RohitChavan16** [comment]
Thanks for the review!

I’ve addressed the requested changes:
Added the success toast to the DrawIO top save handler (handleDrawioSave)
Updated the toast position to bottom-left for consistency
Switched from react-hot-toast to sonner and removed the previously added toast.

The updates are pushed. Please let me know if anything else is needed. Thank you!

**Review by Biki-dev — APPROVED** [review]
thanks for the pr and the changes ....
i made some fixes
1. Added i18n support
2. Fixed the issue where the save toast was running only once
Thanks you
ready to marge...

File: app/[lang]/page.tsx [hunk 1]
```diff
@@ -58,10 +61,17 @@ export default function Home() {
     // We use mouse position to determine if the user is interacting with draw.io
     const handleDrawioSave = useCallback(() => {
         if (!mouseOverDrawioRef.current) return
-        if (isSavingRef.current) return
```
Comment (DayuanJiang) [inline app/[lang]/page.tsx]: could you tell me the reason why you removed this?

**Comment by DayuanJiang** [comment]
Thanks! I have fixed some small issues.

**Review by Biki-dev — COMMENTED** [review]
@DayuanJiang Sorry for the confusion. What I meant is that the issue about showing a confirmation popup after saving locally from the left panel, not triggering a download. Since the browser already shows the downloaded file in the top-right corner, is there anything incorrect in my understanding?

I’ve also created an issue for this bug: #506
